import React, { Component, Suspense, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { AnimatePresence, motion, useScroll, useSpring } from 'framer-motion';
import { FiArrowDownRight, FiArrowUpRight, FiChevronUp, FiCode, FiDownload, FiExternalLink, FiGithub, FiLinkedin, FiMail, FiMenu, FiMoon, FiSearch, FiSun, FiX } from 'react-icons/fi';
import skills from './data/skills.json';
import projects from './data/projects.json';
import experience from './data/experience.json';
import testimonials from './data/testimonials.json';
import type { Experience, Project, SkillGroup, Testimonial } from './types';
import './styles.css';

const typedSkills = skills as SkillGroup[], typedProjects = projects as Project[], typedExperience = experience as Experience[], typedTestimonials = testimonials as Testimonial[];
const reveal = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .15 }, transition: { duration: .55 } };
const SectionTitle = ({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) => <motion.div {...reveal} className="mb-10 max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="lead mt-4">{copy}</p>}</motion.div>;
const Button = ({ children, to, secondary = false }: { children: React.ReactNode; to: string; secondary?: boolean }) => <Link className={`btn ${secondary ? 'btn-secondary' : ''}`} to={to}>{children}<FiArrowUpRight /></Link>;

function ThemeToggle() { const [dark,setDark] = useState(localStorage.theme !== 'light'); useEffect(()=>{ document.documentElement.classList.toggle('dark',dark); localStorage.theme=dark?'dark':'light' },[dark]); return <button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle color theme">{dark ? <FiSun/> : <FiMoon/>}</button> }
function Header() { const [open,setOpen]=useState(false); const links=[['/','Home'],['/about','About'],['/skills','Skills'],['/projects','Projects'],['/experience','Experience'],['/contact','Contact']]; return <header><Link to="/" className="logo" aria-label="Ademola Olalekan home">A.O<span>.</span></Link><nav className={open?'open':''}>{links.map(([to,label])=><NavLink end={to==='/' } onClick={()=>setOpen(false)} key={to} to={to}>{label}</NavLink>)}</nav><div className="header-actions"><ThemeToggle/><button onClick={()=>setOpen(!open)} className="icon-button menu" aria-label="Toggle navigation">{open?<FiX/>:<FiMenu/>}</button></div></header> }
function Shell({ children }: {children: React.ReactNode}) { const {scrollYProgress}=useScroll(); const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:25}); const [top,setTop]=useState(false); const loc=useLocation(); useEffect(()=>{scrollTo(0,0)},[loc.pathname]); useEffect(()=>{const l=()=>setTop(scrollY>600);addEventListener('scroll',l);return()=>removeEventListener('scroll',l)},[]); return <><motion.div className="progress" style={{scaleX}}/><Header/><main>{children}</main>{top&&<button className="to-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top"><FiChevronUp/></button>}<footer><span>© {new Date().getFullYear()} Ademola Olalekan</span><span>Built with intention &amp; React.</span></footer></> }
function Hero() { const phrases=['Full Stack Developer','React & Django Builder','UI-minded Engineer']; const [i,setI]=useState(0); useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%phrases.length),2600);return()=>clearInterval(t)},[]); return <section className="hero"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0}} animate={{opacity:1}}>AVAILABLE FOR OPPORTUNITIES</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}}>I build digital<br/><em>experiences</em> that matter.</motion.h1><motion.p className="typing" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}>I’m a <span>{phrases[i]}</span><b>_</b></motion.p><motion.p className="lead" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35}}>I combine thoughtful interface design with dependable full-stack engineering to make products people want to use.</motion.p><motion.div className="button-row" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.45}}><Button to="/projects">Explore my work</Button><Button to="/contact" secondary>Let’s talk</Button></motion.div><div className="socials"><a href="https://github.com" aria-label="GitHub"><FiGithub/>Adebills</a><a href="https://linkedin.com" aria-label="LinkedIn"><FiLinkedin/>Ademola Adedolapo</a><a href="mailto:hello@example.com" aria-label="Email"><FiMail/>ademolabillions@gmail.com</a></div></div><motion.div className="portrait-wrap" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.7}}><div className="orbit orbit-one"/><div className="portrait"><span>A.O</span><small>YOUR PHOTO<br/>GOES HERE</small></div><div className="floating-card"><FiCode/><span>Clean code<br/><b>Human-first</b></span></div></motion.div><a className="scroll-cue" href="#intro">SCROLL TO DISCOVER <FiArrowDownRight/></a></section> }
function Home() { return <><Hero/><section id="intro" className="section split"><motion.div {...reveal}><p className="eyebrow">01 / A SHORT INTRODUCTION</p><h2>Engineering with an <em>eye for feeling.</em></h2></motion.div><motion.div {...reveal}><p className="lead">I’m Ademola, a full-stack developer who enjoys making complex things feel simple. From robust Django APIs to expressive React interfaces, I care about the entire journey.</p><Button to="/about" secondary>More about me</Button></motion.div></section><section className="section stats">{[['06','Selected projects'],['04','Core disciplines'],['∞','Curiosity to learn']].map(([n,l])=><motion.div {...reveal} key={l}><strong>{n}</strong><span>{l}</span></motion.div>)}</section><FeaturedProjects/><section className="section callout"><motion.div {...reveal}><p className="eyebrow">HAVE A PROJECT IN MIND?</p><h2>Let’s make it <em>exceptional.</em></h2><Button to="/contact">Start a conversation</Button></motion.div></section></> }
function FeaturedProjects() { return <section className="section"><SectionTitle eyebrow="02 / SELECTED WORK" title="A few things I’m proud to have built."/><div className="project-grid">{typedProjects.slice(0,3).map(p=><ProjectCard project={p} key={p.id}/>)}</div><div className="mt-8"><Button to="/projects" secondary>View all projects</Button></div></section> }
function ProjectCard({project:p}:{project:Project}) { return <motion.article {...reveal} className="project-card"><div className={`project-image bg-gradient-to-br ${p.accent}`}><span className="window-dots">● ● ●</span><FiCode/><span>{p.category}</span></div><div className="project-body"><div className="project-meta"><span>{p.tech.slice(0,2).join(' · ')}</span><Link to={`/projects#${p.id}`} aria-label={`View ${p.title}`}><FiArrowUpRight/></Link></div><h3>{p.title}</h3><p>{p.description}</p></div></motion.article> }
function About() { return <PageIntro eyebrow="ABOUT ME" title={<>A curious builder with a <em>product mindset.</em></>} copy="I care equally about how software works and how it makes people feel."><section className="section split"><div><p className="eyebrow">MY JOURNEY</p><h2>From questions to <em>craft.</em></h2></div><div className="prose"><p>What began as curiosity about how the web works became a practice of designing useful, accessible experiences. I’m drawn to the seam where thoughtful design meets solid engineering.</p><p>Today, I bring a calm, collaborative approach to building digital products — asking the right questions, sweating the details, and always learning.</p><a className="text-link" href="/resume.pdf" download><FiDownload/> Download resume</a></div></section><section className="section"><SectionTitle eyebrow="EXPERIENCE" title="Making progress, one meaningful milestone at a time."/><Timeline/></section><section className="section stats fun-facts">{[['☕','Coffee-fuelled problem solver'],['✦','Design systems enthusiast'],['⌘','Always shipping and learning']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section></PageIntro> }
function Skills() { return <PageIntro eyebrow="TECHNICAL TOOLKIT" title={<>Tools I use to bring <em>ideas to life.</em></>} copy="A practical toolkit, continuously sharpened by building real things."><section className="section skills-grid">{typedSkills.map(group=><motion.div {...reveal} className="skill-group glass" key={group.category}><h3>{group.category}</h3>{group.skills.map(s=><div className="skill" key={s.name}><div><span>{s.name}</span><small>{s.level}%</small></div><div className="skill-track"><motion.i initial={{width:0}} whileInView={{width:`${s.level}%`}} viewport={{once:true}} transition={{duration:1}}/></div></div>)}</motion.div>)}</section></PageIntro> }
function Projects() { const [term,setTerm]=useState(''); const [filter,setFilter]=useState('All'); const cats=['All',...new Set(typedProjects.map(p=>p.category))]; const visible=useMemo(()=>typedProjects.filter(p=>(filter==='All'||p.category===filter)&&`${p.title} ${p.tech.join(' ')}`.toLowerCase().includes(term.toLowerCase())),[term,filter]); return <PageIntro eyebrow="PROJECT ARCHIVE" title={<>Turning complex problems into <em>clear experiences.</em></>} copy="A selection of projects across interfaces, APIs and full-stack systems."><section className="section"><div className="project-controls"><label><FiSearch/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search projects" aria-label="Search projects"/></label><div className="filters">{cats.map(c=><button onClick={()=>setFilter(c)} className={filter===c?'active':''} key={c}>{c}</button>)}</div></div><div className="project-grid">{visible.map(p=><ProjectCard project={p} key={p.id}/>)}</div>{visible.length===0&&<p className="empty">No projects match that search.</p>}</section><section className="section"><SectionTitle eyebrow="HOW I THINK" title="The details behind the deliverable."/><div className="detail-grid">{typedProjects.slice(0,3).map(p=><article className="glass" id={p.id} key={p.id}><h3>{p.title}</h3><p><b>Challenge</b>{p.challenge}</p><p><b>What I learned</b>{p.learned}</p><div className="card-links"><a href={p.github}><FiGithub/> Code</a><a href={p.demo}><FiExternalLink/> Demo</a></div></article>)}</div></section></PageIntro> }
function Timeline(){return <div className="timeline">{typedExperience.map(e=><motion.article {...reveal} key={e.period}><span className="dot"/><p className="eyebrow">{e.period}</p><h3>{e.role}</h3><b>{e.company}</b><p>{e.description}</p></motion.article>)}</div>}
function ExperiencePage(){return <PageIntro eyebrow="EXPERIENCE" title={<>Growing through work that <em>matters.</em></>} copy="A timeline of hands-on building, intentional growth and the next challenge."><section className="section"><Timeline/></section></PageIntro>}
function Testimonials(){return <PageIntro eyebrow="KIND WORDS" title={<>Built on trust and <em>good collaboration.</em></>}><section className="section testimonial-grid">{typedTestimonials.map(t=><motion.figure {...reveal} className="glass" key={t.name}><blockquote>“{t.quote}”</blockquote><figcaption><span>{t.name[0]}</span><div><b>{t.name}</b><small>{t.role}</small></div></figcaption></motion.figure>)}</section></PageIntro>}
function Blog(){return <PageIntro eyebrow="FIELD NOTES" title={<>Ideas, lessons and <em>things I’m learning.</em></>} copy="Writing is coming soon. Until then, let’s connect on LinkedIn or GitHub."><section className="section empty-state"><FiCode/><h3>Thoughtful notes are on their way.</h3><Button to="/contact" secondary>Get in touch</Button></section></PageIntro>}
function Contact(){const [sent,setSent]=useState(false); const submit=(e:React.FormEvent)=>{e.preventDefault();const url=import.meta.env.VITE_FORMSPREE_ENDPOINT;if(url) fetch(url,{method:'POST',body:new FormData(e.target as HTMLFormElement),headers:{Accept:'application/json'}}).then(()=>setSent(true));else setSent(true)};return <PageIntro eyebrow="CONTACT" title={<>Have an opportunity? <em>Let’s talk.</em></>} copy="I’m open to full-stack roles, meaningful collaborations and interesting problems."><section className="section contact-layout"><div><h3>Start a conversation.</h3><p>Whether it’s a role, a project, or simply an idea worth exploring — my inbox is open.</p><a className="contact-link" href="mailto:hello@example.com"><FiMail/>hello@example.com</a><a className="contact-link" href="https://github.com"><FiGithub/>github.com/your-handle</a><a className="contact-link" href="https://linkedin.com"><FiLinkedin/>linkedin.com/in/your-handle</a><p className="location">Based in Lagos, Nigeria · Working globally</p></div><form onSubmit={submit} className="glass">{sent?<div className="sent"><h3>Thank you.</h3><p>Your message has been received. I’ll get back to you soon.</p></div>:<><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Message<textarea required name="message" rows={5} placeholder="Tell me a little about the opportunity..."/></label><button className="btn" type="submit">Send message <FiArrowUpRight/></button></>}</form></section></PageIntro>}
function PageIntro({eyebrow,title,copy,children}:{eyebrow:string;title:React.ReactNode;copy?:string;children:React.ReactNode}){return <><section className="page-hero"><motion.div {...reveal}><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy&&<p className="lead">{copy}</p>}</motion.div></section>{children}</>}
function NotFound(){return <section className="page-hero not-found"><p className="eyebrow">ERROR 404</p><h1>That page has <em>moved on.</em></h1><Button to="/">Back home</Button></section>}
class ErrorBoundary extends Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="error"><h1>Something went wrong.</h1><a href="/">Return home</a></div>:this.props.children}}
function App(){return <ErrorBoundary><BrowserRouter><Shell><Suspense fallback={<div className="loader">AM<span>.</span></div>}><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/skills" element={<Skills/>}/><Route path="/projects" element={<Projects/>}/><Route path="/experience" element={<ExperiencePage/>}/><Route path="/testimonials" element={<Testimonials/>}/><Route path="/blog" element={<Blog/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></Shell></BrowserRouter></ErrorBoundary>};
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
